const express = require('express');
const jwt = require('jsonwebtoken');
const { body, validationResult } = require('express-validator');
const AudioClip = require('../models/AudioClip');
const upload = require('../middleware/upload');
const { authenticateAdmin } = require('../middleware/auth');
const { validatePassword, generateSecurePassword } = require('../middleware/passwordValidation');
const config = require('../config');
const { uploadToGridFS, deleteFromGridFS } = require('../utils/gridfs');
const path = require('path');

const router = express.Router();

// Admin login
router.post('/login', [
  body('password').notEmpty().withMessage('Password is required')
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    const { password } = req.body;
    
    // Simple password check (in production, use proper authentication)
    if (password !== config.ADMIN_PASSWORD) {
      return res.status(401).json({ msg: 'Invalid credentials' });
    }

    // Generate JWT token
    const token = jwt.sign(
      { role: 'admin', id: 'admin' },
      config.JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.json({ token, msg: 'Login successful' });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ msg: 'Server error' });
  }
});

// Upload audio file
router.post('/upload', authenticateAdmin, upload.single('audio'), [
  body('title').notEmpty().trim().withMessage('Title is required'),
  ...validatePassword
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    if (!req.file) {
      return res.status(400).json({ msg: 'Audio file is required' });
    }

    const { title, password } = req.body;

    // Generate unique filename
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    const filename = `audio-${uniqueSuffix}${path.extname(req.file.originalname)}`;

    // Upload to GridFS
    const gridFSResult = await uploadToGridFS(
      req.file.buffer,
      filename,
      {
        originalName: req.file.originalname,
        mimeType: req.file.mimetype,
        title: title
      }
    );

    // Create new audio clip record
    const audioClip = new AudioClip({
      title,
      filename: filename,
      originalName: req.file.originalname,
      gridFSFileId: gridFSResult.fileId,
      fileSize: req.file.size,
      mimeType: req.file.mimetype,
      password, // Will be hashed by pre-save middleware
      isAutoGenerated: false
    });

    await audioClip.save();

    res.status(201).json({
      msg: 'Audio clip uploaded successfully',
      clip: {
        id: audioClip._id,
        title: audioClip.title,
        filename: audioClip.filename,
        fileSize: audioClip.fileSize,
        createdAt: audioClip.createdAt
      }
    });
  } catch (error) {
    console.error('Upload error:', error);
    res.status(500).json({ msg: 'Server error during upload' });
  }
});

// Get all audio clips (admin view)
router.get('/clips', authenticateAdmin, async (req, res) => {
  try {
    const clips = await AudioClip.find({ isActive: true })
      .select('-password') // Exclude password from response
      .sort({ createdAt: -1 });

    res.json(clips);
  } catch (error) {
    console.error('Get clips error:', error);
    res.status(500).json({ msg: 'Server error' });
  }
});

// Delete audio clip
router.delete('/clips/:id', authenticateAdmin, async (req, res) => {
  try {
    const clip = await AudioClip.findById(req.params.id);
    
    if (!clip) {
      return res.status(404).json({ msg: 'Audio clip not found' });
    }

    // Delete file from GridFS (if it exists)
    if (clip.gridFSFileId) {
      try {
        await deleteFromGridFS(clip.gridFSFileId);
      } catch (gridFSError) {
        // Log but don't fail - file might not exist in GridFS (old records or already deleted)
        console.warn('Warning: Could not delete from GridFS:', gridFSError.message);
      }
    }

    // Delete legacy file from filesystem if it exists (for old records)
    if (clip.filePath) {
      const fs = require('fs');
      try {
        if (fs.existsSync(clip.filePath)) {
          fs.unlinkSync(clip.filePath);
        }
      } catch (fsError) {
        console.warn('Warning: Could not delete legacy file from filesystem:', fsError.message);
      }
    }

    // Delete from database
    await AudioClip.findByIdAndDelete(req.params.id);

    res.json({ msg: 'Audio clip deleted successfully' });
  } catch (error) {
    console.error('Delete error:', error);
    res.status(500).json({ msg: 'Server error' });
  }
});

// Generate share link for audio clip
router.get('/clips/:id/share', authenticateAdmin, async (req, res) => {
  try {
    const clip = await AudioClip.findById(req.params.id);
    
    if (!clip) {
      return res.status(404).json({ msg: 'Audio clip not found' });
    }

    const shareLink = `${req.protocol}://${req.get('host')}/audio/${clip._id}`;
    
    res.json({ shareLink });
  } catch (error) {
    console.error('Share link error:', error);
    res.status(500).json({ msg: 'Server error' });
  }
});

// Generate secure password
router.post('/generate-password', authenticateAdmin, async (req, res) => {
  try {
    const { type = 'secure' } = req.body;
    
    let password;
    
    switch (type) {
      case 'secure':
        password = generateSecurePassword({ length: 12, includeUppercase: true, includeLowercase: true, includeNumbers: true });
        break;
      case 'memorable':
        // Generate memorable password using words
        const words = ['apple', 'banana', 'cherry', 'dragon', 'eagle', 'forest', 'garden', 'happy',
                      'island', 'jungle', 'knight', 'lizard', 'mountain', 'ocean', 'panda', 'queen',
                      'river', 'sunset', 'tiger', 'umbrella', 'violet', 'winter', 'yellow', 'zebra'];
        const selectedWords = [];
        for (let i = 0; i < 3; i++) {
          selectedWords.push(words[Math.floor(Math.random() * words.length)]);
        }
        password = selectedWords.join('-');
        break;
      case 'pin':
        password = Math.floor(100000 + Math.random() * 900000).toString(); // 6-digit PIN
        break;
      default:
        password = generateSecurePassword({ length: 12, includeUppercase: true, includeLowercase: true, includeNumbers: true });
    }
    
    res.json({ password });
  } catch (error) {
    console.error('Generate password error:', error);
    res.status(500).json({ msg: 'Server error' });
  }
});

module.exports = router;
