const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const audioClipSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 100
  },
  filename: {
    type: String,
    required: true
  },
  originalName: {
    type: String,
    required: true
  },
  gridFSFileId: {
    type: mongoose.Schema.Types.ObjectId,
    required: false, // Optional for backward compatibility with old records
    ref: 'audioFiles'
  },
  // Legacy field for old records (before GridFS migration)
  filePath: {
    type: String,
    required: false
  },
  fileSize: {
    type: Number,
    required: true
  },
  mimeType: {
    type: String,
    required: true
  },
  password: {
    type: String,
    required: true
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  accessCount: {
    type: Number,
    default: 0
  },
  lastAccessed: {
    type: Date
  },
  isActive: {
    type: Boolean,
    default: true
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Hash password before saving
audioClipSchema.pre('save', async function(next) {
  if (this.isModified('password')) {
    this.password = await bcrypt.hash(this.password, 12);
  }
  next();
});

// Compare password method
audioClipSchema.methods.comparePassword = async function(candidatePassword) {
  return bcrypt.compare(candidatePassword, this.password);
};

// Update last accessed
audioClipSchema.methods.updateAccess = function() {
  this.accessCount += 1;
  this.lastAccessed = new Date();
  return this.save();
};

module.exports = mongoose.model('AudioClip', audioClipSchema);
